### ISSUE TITLE
Are you actually fixing or even trying to fix any of the issues that pop up? ...

### ISSUE THREAD

**Issue by hfellerhoff** [hfellerhoff/openipa#108]
## Details
Are you actually fixing or even trying to fix any of the issues that pop up? I haven't seen anything fixed since I first found this site and sent my first feedback (almost 4 months ago)! 

## French Text 
No text provided.
  
---

This is an autogenerated issue created from an Open IPA feedback form submission. The form is accessible at https://www.openipa.org/transcription.

**Comment by hfellerhoff** [comment]
As a full time student, I've been busy finishing up my undergraduate work. I'll have more time in the next few weeks to fix issues - thank you for your patience!

**Comment by LittleWishy** [comment]
It's been two years since this was submitted; any updates? I don't see any changes.
